service: vue-twilio-app  # Name of the new service
runtime: nodejs18          # Custom runtime to use a Dockerfile
               # Use flexible environment for WebSocket support


instance_class: F2

handlers:
  - url: /favicon.ico
    static_files: dist/favicon.ico
    upload: dist/favicon.ico

  - url: /js
    static_dir: dist/js

  - url: /css
    static_dir: dist/css

  - url: /img
    static_dir: dist/img

  - url: /fonts
    static_dir: dist/fonts

  - url: /.*\.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|eot|ttf|otf)
    static_files: dist/\1
    upload: dist/.*\.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|eot|ttf|otf)

  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html


